#!/usr/bin/env python3
"""
Replace function calls with method calls in registration-manager.php
"""

file_path = r"C:\Users\simon\Documents\Sites\mjpery-wordpress\wp-content\plugins\mj-member\includes\core\ajax\admin\registration-manager.php"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Define all replacements as a list of tuples
replacements = [
    ('mj_regmgr_verify_request(', '$this->verifyRequest('),
    ('mj_regmgr_to_bool(', '$this->toBool('),
    ('mj_regmgr_format_date(', '$this->formatDate('),
    ('mj_regmgr_build_event_sidebar_item(', '$this->buildEventSidebarItem('),
    ('mj_regmgr_get_member_avatar_url(', '$this->getMemberAvatarUrl('),
    ('mj_regmgr_format_datetime_compact(', '$this->formatDatetimeCompact('),
    ('mj_regmgr_format_date_compact(', '$this->formatDateCompact('),
    ('mj_regmgr_format_time_compact(', '$this->formatTimeCompact('),
    ('mj_regmgr_occurrence_status_from_front(', '$this->occurrenceStatusFromFront('),
    ('mj_regmgr_occurrence_status_to_front(', '$this->occurrenceStatusToFront('),
    ('mj_regmgr_sanitize_time_value(', '$this->sanitizeTimeValue('),
    ('mj_regmgr_sanitize_date_value(', '$this->sanitizeDateValue('),
    ('mj_regmgr_sanitize_occurrence_generator_plan(', '$this->sanitizeOccurrenceGeneratorPlan('),
    ('mj_regmgr_derive_generator_plan_from_schedule(', '$this->deriveGeneratorPlanFromSchedule('),
    ('mj_regmgr_merge_generator_plans(', '$this->mergeGeneratorPlans('),
    ('mj_regmgr_extract_occurrence_generator_from_payload(', '$this->extractOccurrenceGeneratorFromPayload('),
    ('mj_regmgr_extract_occurrence_generator_from_event(', '$this->extractOccurrenceGeneratorFromEvent('),
    ('mj_regmgr_schedule_payload_has_occurrence_entities(', '$this->schedulePayloadHasOccurrenceEntities('),
    ('mj_regmgr_should_allow_occurrence_fallback(', '$this->shouldAllowOccurrenceFallback('),
    ('mj_regmgr_prepare_event_occurrence_rows(', '$this->prepareEventOccurrenceRows('),
    ('mj_regmgr_format_event_occurrences_for_front(', '$this->formatEventOccurrencesForFront('),
    ('mj_regmgr_find_next_occurrence(', '$this->findNextOccurrence('),
    ('mj_regmgr_build_event_schedule_info(', '$this->buildEventScheduleInfo('),
    ('mj_regmgr_get_event_emoji_value(', '$this->getEventEmojiValue('),
    ('mj_regmgr_get_event_cover_url(', '$this->getEventCoverUrl('),
    ('mj_regmgr_decode_json_field(', '$this->decodeJsonField('),
    ('mj_regmgr_serialize_event_summary(', '$this->serializeEventSummary('),
    ('mj_regmgr_prepare_event_form_values(', '$this->prepareEventFormValues('),
    ('mj_regmgr_collect_event_editor_assets(', '$this->collectEventEditorAssets('),
    ('mj_regmgr_build_event_update_payload(', '$this->buildEventUpdatePayload('),
    ('mj_regmgr_get_schedule_weekdays(', '$this->getScheduleWeekdays('),
    ('mj_regmgr_get_schedule_month_ordinals(', '$this->getScheduleMonthOrdinals('),
    ('mj_regmgr_sanitize_weekday_times(', '$this->sanitizeWeekdayTimes('),
    ('mj_regmgr_sanitize_recurrence_exceptions(', '$this->sanitizeRecurrenceExceptions('),
    ('mj_regmgr_ensure_notes_table(', '$this->ensureNotesTable('),
    ('mj_regmgr_get_notes_dynfields(', '$this->getNotesDynfields('),
    ('mj_regmgr_event_allows_attendance_without_registration(', '$this->eventAllowsAttendanceWithoutRegistration('),
    ('mj_regmgr_ensure_attendance_registration(', '$this->ensureAttendanceRegistration('),
    ('mj_regmgr_normalize_hex_color(', '$this->normalizeHexColor('),
    ('mj_regmgr_format_event_datetime(', '$this->formatEventDatetime('),
    ('mj_regmgr_parse_event_datetime(', '$this->parseEventDatetime('),
    ('mj_regmgr_parse_recurrence_until(', '$this->parseRecurrenceUntil('),
    ('mj_regmgr_events_supports_primary_animateur(', '$this->eventsSupportsPrimaryAnimateur('),
    ('mj_regmgr_fill_schedule_values(', '$this->fillScheduleValues('),
    ('mj_regmgr_user_can_manage_locations(', '$this->userCanManageLocations('),
    ('mj_regmgr_build_location_lookup_query(', '$this->buildLocationLookupQuery('),
    ('mj_regmgr_format_location_payload(', '$this->formatLocationPayload('),
    ('mj_regmgr_resolve_schedule_exceptions(', '$this->resolveScheduleExceptions('),
    ('mj_regmgr_build_location_map_preview_url(', '$this->buildLocationMapPreviewUrl('),
    ('mj_regmgr_build_location_map_link(', '$this->buildLocationMapLink('),
    ('mj_regmgr_get_event_photos(', '$this->getEventPhotos('),
    ('mj_regmgr_upload_event_photo(', '$this->uploadEventPhoto('),
    ('mj_regmgr_update_occurrences(', '$this->updateOccurrences('),
    ('mj_regmgr_save_event_occurrences(', '$this->saveEventOccurrences('),
    ('mj_regmgr_get_members(', '$this->getMembers('),
    ('mj_regmgr_get_member_details(', '$this->getMemberDetails('),
    ('mj_regmgr_update_member(', '$this->updateMember('),
    ('mj_regmgr_update_member_trusted_status(', '$this->updateMemberTrustedStatus('),
    ('mj_regmgr_get_member_registrations(', '$this->getMemberRegistrations('),
    ('mj_regmgr_mark_membership_paid(', '$this->markMembershipPaid('),
    ('mj_regmgr_create_membership_payment_link(', '$this->createMembershipPaymentLink('),
    ('mj_regmgr_update_member_idea(', '$this->updateMemberIdea('),
    ('mj_regmgr_delete_member_idea(', '$this->deleteMemberIdea('),
    ('mj_regmgr_update_member_photo(', '$this->updateMemberPhoto('),
    ('mj_regmgr_delete_member_photo(', '$this->deleteMemberPhoto('),
    ('mj_regmgr_capture_member_photo(', '$this->captureMemberPhoto('),
    ('mj_regmgr_create_member_message(', '$this->createMemberMessage('),
    ('mj_regmgr_delete_member_message(', '$this->deleteMemberMessage('),
    ('mj_regmgr_update_member_notification(', '$this->updateMemberNotification('),
    ('mj_regmgr_delete_member_notification(', '$this->deleteMemberNotification('),
    ('mj_regmgr_reset_member_password(', '$this->resetMemberPassword('),
    ('mj_regmgr_create_member_nextcloud_login(', '$this->createMemberNextcloudLogin('),
    ('mj_regmgr_delete_member(', '$this->deleteMember('),
    ('mj_regmgr_sync_member_badge(', '$this->syncMemberBadge('),
    ('mj_regmgr_adjust_member_xp(', '$this->adjustMemberXp('),
    ('mj_regmgr_toggle_member_trophy(', '$this->toggleMemberTrophy('),
    ('mj_regmgr_award_member_action(', '$this->awardMemberAction('),
    ('mj_regmgr_update_social_link(', '$this->updateSocialLink('),
    ('mj_regmgr_update_member_leave_quotas(', '$this->updateMemberLeaveQuotas('),
    ('mj_regmgr_save_member_work_schedule(', '$this->saveMemberWorkSchedule('),
    ('mj_regmgr_delete_member_work_schedule(', '$this->deleteMemberWorkSchedule('),
    ('mj_regmgr_save_member_dynfields(', '$this->saveMemberDynfields('),
    ('mj_regmgr_get_employee_documents(', '$this->getEmployeeDocuments('),
    ('mj_regmgr_upload_employee_document(', '$this->uploadEmployeeDocument('),
    ('mj_regmgr_update_employee_document(', '$this->updateEmployeeDocument('),
    ('mj_regmgr_delete_employee_document(', '$this->deleteEmployeeDocument('),
    ('mj_regmgr_download_employee_document(', '$this->downloadEmployeeDocument('),
    ('mj_regmgr_save_job_profile(', '$this->saveJobProfile('),
    ('mj_regmgr_get_favorites(', '$this->getFavorites('),
    ('mj_regmgr_toggle_favorite(', '$this->toggleFavorite('),
    ('mj_regmgr_generate_ai_text(', '$this->generateAiText('),
    ('mj_regmgr_publish_event(', '$this->publishEvent('),
    ('mj_regmgr_get_event_details(', '$this->getEventDetails('),
    ('mj_regmgr_get_event_editor(', '$this->getEventEditor('),
    ('mj_regmgr_update_event(', '$this->updateEvent('),
    ('mj_regmgr_create_event(', '$this->createEvent('),
    ('mj_regmgr_delete_event(', '$this->deleteEvent('),
    ('mj_regmgr_get_registrations(', '$this->getRegistrations('),
    ('mj_regmgr_search_members(', '$this->searchMembers('),
    ('mj_regmgr_add_registration(', '$this->addRegistration('),
    ('mj_regmgr_update_registration(', '$this->updateRegistration('),
    ('mj_regmgr_delete_registration(', '$this->deleteRegistration('),
    ('mj_regmgr_update_attendance(', '$this->updateAttendance('),
    ('mj_regmgr_bulk_attendance(', '$this->bulkAttendance('),
    ('mj_regmgr_validate_payment(', '$this->validatePayment('),
    ('mj_regmgr_cancel_payment(', '$this->cancelPayment('),
    ('mj_regmgr_create_quick_member(', '$this->createQuickMember('),
    ('mj_regmgr_get_member_notes(', '$this->getMemberNotes('),
    ('mj_regmgr_save_member_note(', '$this->saveMemberNote('),
    ('mj_regmgr_delete_member_note(', '$this->deleteMemberNote('),
    ('mj_regmgr_get_payment_qr(', '$this->getPaymentQr('),
    ('mj_regmgr_get_location(', '$this->getLocation('),
    ('mj_regmgr_save_location(', '$this->saveLocation('),
    ('mj_regmgr_update_registration_occurrences(', '$this->updateRegistrationOccurrences('),
    ('mj_regmgr_delete_member_testimonial(', '$this->deleteMemberTestimonial('),
    ('mj_regmgr_update_member_testimonial_status(', '$this->updateMemberTestimonialStatus('),
    ('mj_regmgr_toggle_testimonial_featured(', '$this->toggleTestimonialFeatured('),
    ('mj_regmgr_edit_testimonial_content(', '$this->editTestimonialContent('),
    ('mj_regmgr_add_testimonial_comment(', '$this->addTestimonialComment('),
    ('mj_regmgr_edit_testimonial_comment(', '$this->editTestimonialComment('),
    ('mj_regmgr_delete_testimonial_comment(', '$this->deleteTestimonialComment('),
    ('mj_regmgr_add_testimonial_reaction(', '$this->addTestimonialReaction('),
    ('mj_regmgr_remove_testimonial_reaction(', '$this->removeTestimonialReaction('),
    ('mj_regmgr_get_member_level_progression(', '$this->getMemberLevelProgression('),
    ('mj_regmgr_get_member_badges_payload(', '$this->getMemberBadgesPayload('),
    ('mj_regmgr_prepare_member_badge_entry(', '$this->prepareMemberBadgeEntry('),
    ('mj_regmgr_is_badge_complete(', '$this->isBadgeComplete('),
    ('mj_regmgr_normalize_notification_type_key(', '$this->normalizeNotificationTypeKey('),
    ('mj_regmgr_get_notification_type_emoji(', '$this->getNotificationTypeEmoji('),
    ('mj_regmgr_extract_notification_emoji(', '$this->extractNotificationEmoji('),
    ('mj_regmgr_format_member_notification(', '$this->formatMemberNotification('),
    ('mj_regmgr_get_member_trophies_payload(', '$this->getMemberTrophiesPayload('),
    ('mj_regmgr_get_member_actions_payload(', '$this->getMemberActionsPayload('),
    ('mj_regmgr_create_notes_table_if_not_exists(', '$this->createNotesTableIfNotExists('),
]

# Perform all replacements and count them
total_replacements = 0
for old, new in replacements:
    count = content.count(old)
    if count > 0:
        content = content.replace(old, new)
        total_replacements += count

# Write the file back
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Total replacements made: " + str(total_replacements))
